### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by brandtdaniels** [Brightify/Cuckoo#174]
Any plans on supporting Swift Package Manager installs?

**Comment by krummler** [comment]
Hi there! Since SPM is integrated into Xcode 11 it would be really great to be able to use this library using SPM too.

**Comment by MatyasKriz** [comment]
Hey, @krummler. I think about SwiftPM often, I'll update it to latest version (it's an old PR) and see what I can do.

**Comment by krummler** [comment]
I merged master into the PR branch on: https://github.com/krummler/Cuckoo/tree/feature/swift-PM. Importing into XCode11 works fine, so does importing the library and using the generated mocks/stubs. 
The step I'm not sure about, is how to run the generator? For now I copied the `GeneratedMocks.swift` into place just to try it out.

**Comment by MatyasKriz** [comment]
The reason the PR wasn't originally merged was because there was no easy way to get the `run` script into your project directory.

That's why it also adds a clause into `README.md` with instructions on how to obtain it.

```
curl -Lo "Cuckoo.zip" `curl "https://api.github.com/repos/Brightify/Cuckoo/releases/latest" | grep -oe '"zipball_url":\s*"[^" ]*"' | grep -oe 'http[^" ]*'`
unzip -p Cuckoo.zip "*Cuckoo*/run" > run
chmod +x run
rm "Cuckoo.zip"
```

It's not very nice (I'm not sure if you can download just the `run` script itself instead, that would be grand) and it's not automatic. The user has to do it manually.

Could you please try to look into some ways of making this process as simple as possible? As opposed to Cocoapods, SwiftPM had no way of running a command after installation. If that changed, this last issue would be fixed.

**Comment by TadeasKriz** [comment]
When using packages in Xcode, users could probably add the run script as before. The only thing is getting the run script. Another possibility would be having a Homebrew release which could be just run in the build script.

**Comment by krummler** [comment]
I'm pretty new to SPM to be honest, but if I understand currectly the project kicks off a script that downloads the generator separately? I'm not sure if that's possible to be honest.
The generator is in a subfolder of the repo with it's own, this might be hard to get compatible:
     
> Packages are Git repositories, tagged with semantic versions, containing a Package.swift file at their root. Initializing the package created a Package.swift file, but to make it a usable package we need to initialize a Git repository with at least one version tag.

I'm tinkering around with merging the package definitions into one, that way the `cuckoo_generator` command might just be runnable when getting the main package. So far no luck though.

**Comment by krummler** [comment]
I'm not quite sure how to run swift packages from within Xcode?

To work around this, I'm doing the following in my own project:

- Add a new Package Dependency in Xcode 11 (File -> Swift Packages -> Add Package Dependency)
- For now I add https://github.com/krummler/Cuckoo, branch 'feature/swift-PM'
- Add it to the test target

To generate the mock file:
- Created a Package.swift in the project root:

```
// swift-tools-version:4.2
import PackageDescription

let package = Package(
    name: "Custom",
    dependencies: [
      .package(url: "https://github.com/krummler/Cuckoo", .branch("feature/swift-PM"))
    ]
)
```

Alter the run-command part in the Build Phases to be:
```
cd "${PROJECT_DIR}"
swift run cuckoo_generator generate --testable "${PROJECT_NAME}" \
```
The first run is slow, because thats when it fetches dependencies, after that it's fine. 

This does mean Cuckoo is installed twice: once through Xcode, and once through the command line (using the Package.swift added in the project root), anyone know how to get around that?

**Comment by MatyasKriz** [comment]
I managed to reduce the line to get the `run` script into a single short line.

```
curl https://raw.githubusercontent.com/Brightify/Cuckoo/master/run > run && chmod +x run
```

That makes it much nicer and simpler to use.

@krummler the `run` script takes care of everything related to generating the mocks, don't worry. The main step is getting the `run` script itself, on its own, it checks whether it can build the generator or has to download it from GitHub.

**Comment by krummler** [comment]
But the downloaded repository already contains the generator right? If it's possible to simply use the already downloaded generator, there's no need to run any script anymore. 

Simply run `swift run cuckoo_generator generate` when generating mocks and it'll build itself.

**Comment by MatyasKriz** [comment]
I thought that SwiftPM doesn't download the `Generator` folder along with Cuckoo. It does?

Anyway, the preferred way to use the Cuckoo generator is using the `run` script, just like when using Cocoapods or Carthage.

**Comment by krummler** [comment]
Hey there, thanks for the quick response!

When I change the package.swift to also include the Generator sources, it allows the whole thing to be downloaded and run at once. Check out: https://github.com/krummler/Cuckoo/blob/feature/swift-PM/Package.swift.
Now simply adding the package to my project's Package.swift allows me to run the `swift run` command without calling any other scripts beforehand.

A valid package should have a package.swift at the root of the repo, which is why I tried to merge the two packages. See also: https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#require-system-libraries. I'm guessing if you want to keep these separate, the generator should be in it's own git project.

When using SPM, packages are installed either in the .build folder (command line) or derived data (XCode11), neither seems like a particular good place to manually fetch data using curl?

**Comment by TadeasKriz** [comment]
I wouldn't want to split the repository, we had that before and it was a nightmare.

**Comment by flopshot** [comment]
Hi guys,

Just was wondering where the PR https://github.com/Brightify/Cuckoo/pull/193 was in terms of merging it in, modifying it, or scrapping it for another approach? Thanks

**Comment by TadeasKriz** [comment]
Hi @flopshot, we don't currently have enough feedback on the PR to determine whether the current implementation is needed and if it's developer friendly enough.

**Comment by flopshot** [comment]
Thanks @TadeasKriz With regards to this issue, is there any likelihood that support for swift package manager will be added by Xcode 11?

**Comment by brandtdaniels** [comment]
> When using packages in Xcode, users could probably add the run script as before. The only thing is getting the run script. Another possibility would be having a Homebrew release which could be just run in the build script.

I don't commit the project file since swift can generate them on the fly, I wouldn't want to manually add it to the project every time.

**Comment by MatyasKriz** [comment]
Hey everyone! I forgot that we had a SwiftPM issue (of course we have). Version `1.3.2` is ready to roll and should be usable with `SwiftPM`. Be sure to consult `README.md` about the changes as opposed to other package managers. Thanks for the patience and enjoy!
