### ISSUE TITLE
`verify` does not fail asserts

### ISSUE THREAD

**Issue by bmaslakov** [Brightify/Cuckoo#197]
In cuckoo v0.11.3 `verify` does not fail tests.
```
let mock = MockDLGDummyPeerConnectionExt()
// mock.addIceCandidate(RTCIceCandidate.init(sdp: "", sdpMLineIndex: 32, sdpMid: nil))
verify(mock, times(100)).addIceCandidate(any())
```
I replicated the bug in the following repo: https://github.com/bmaslakov/Cuckoo

I described the bug on your slack channel ;)

Thanks!

**Comment by MatyasKriz** [comment]
Hey there, thanks for the report! I looked into the matter, the problem is that the test case is not called at all. Both print debugging and breakpoints didn't get called, the problem was that the test case must be a subclass of `XCTestCase`. The correct declaration of your test class should be `class DLGPeerMediaTests: XCTestCase`, then it will get called correctly and Cuckoo will fail the test. 🙂
