### ISSUE TITLE
Can I split GeneratedMocks file?

### ISSUE THREAD

**Issue by carminelavalle** [Brightify/Cuckoo#202]
I’m working on an app with MVP architecture and the viewControllers extend a BaseViewController.
I want to make tests for all (or most of them) presenter’s methods, so GeneratedMocks.swift file became huge (near 10K lines and counting) so I tried to split the GeneratedMocks.swift file as follows:

_First:_

```
OUTPUT_FILE="$PROJECT_DIR/${PROJECT_NAME}Tests/GeneratedMocksLogin.swift"

INPUT_DIR="${PROJECT_DIR}/${PROJECT_NAME}/Application"

"${PODS_ROOT}/Cuckoo/run" generate --testable "$PROJECT_NAME" \
--output "${OUTPUT_FILE}" \
"$INPUT_DIR/Base/BaseViewController.swift" \
"$INPUT_DIR/Login/Contracts/FileName1.swift"

```
_Second:_

```
OUTPUT_FILE="$PROJECT_DIR/${PROJECT_NAME}Tests/GeneratedMocksRegistration.swift"

INPUT_DIR="${PROJECT_DIR}/${PROJECT_NAME}/Application"

"${PODS_ROOT}/Cuckoo/run" generate --testable "$PROJECT_NAME" \
--output "${OUTPUT_FILE}" \
"$INPUT_DIR/Base/BaseViewController.swift" \
"$INPUT_DIR/Registration/Contracts/FileName1.swift " \
"$INPUT_DIR/Registration/Contracts/FileName2.swift " \
"$INPUT_DIR/Registration/Contracts/FileName3.swift"
```

_and so on._

In the resulting files I receive a duplicate class error (BaseViewController.swift).
If I omit "$INPUT_DIR/Base/BaseViewController.swift" from a section (i.e. in "GeneratedMocksRegistration.swift") then the "BaseViewController" methods are not generated in the classes defined into GeneratedMocksRegistration file and therefore the classes do not conform to the BaseViewController

Is it possible to split GeneratedMocks into multiple files as I thought?

**Comment by TadeasKriz** [comment]
Hi @carminelavalle did you find a solution? As far as I know you can split the generated file if you keep all parent and child classes in a single file. Was the file size a problem?

**Comment by carminelavalle** [comment]
Sorry guys, I read the docs and I found that the parameter --output can take a folder as argument, so it skip files instead of generate a single file.

**Comment by TadeasKriz** [comment]
Wow, I forgot we had that, thanks!

**Comment by nhatkhang169** [comment]
Hi @TadeasKriz , 
I can pass a folder as --output parameter to generate files, but the problem is there are too many files and I need to include new generated files to the Test target every time there is a new file to mock.

Should we have an improvement to:
- limit the maximum number of lines of a GeneratedMocks.swift
- if exceeding the limit, the generator auto move the remaining generated content to the next version of generated file like: GeneratedMocks2.swift, GeneratedMocks3.swift and so on.

Currently, my project has 333 files to mock, and GeneratedMocks.swift is 4MB. Xcode stucks when loading the file and it takes a bit long to index and build the project.
Thanks

**Comment by TadeasKriz** [comment]
Hi @nhatkhang169, I understand your usecase and I'm open to approving a PR with such a feature. However since you can generate a mock file for each input, this is not a priority for our core team. If you're willing, you can implement it and send in a pull request. Thanks!

**Comment by MatyasKriz** [comment]
I'd advise against including such a feature. This sounds very much like
feature bloat to me since dividing mocks by file is already included.
It might make sense when we add support for configuration file, but not as
yet another command parameter.

**Comment by nhatkhang169** [comment]
Thanks @TadeasKriz and @MatyasKriz for pointing out. 
My proposal is not about adding a new command parameter. But a predefined value or a configuration setting for the maximum lines per file, this might not be configurable. The generator should still accept a single file as output, but may auto-generates cascading files (with suffixes) if exceeding the limit.

**Comment by MatyasKriz** [comment]
I don't think I understand how you want to give yourself as the user the possibility to opt-in to this file splitting.

It wouldn't feel comfortable for me to force this on all users by default. That's why I wanted to wait until we add support for a configuration file that we can document much better than adding another generator argument to the `README.md`.

If you feel like you really need this feature, add support, create a PR but don't count on it being merged to `Cuckoo/master` until we add support for a configuration file.

Personally, I don't feel like this is a better solution than using the `--output` option to point to a directory, causing it to separate the inputs by file.
Allow me to explain. The user needs to add any new file that is to be compiled to the Xcode project; this can be daunting when you have to do this for every file you add (for example when using `--glob`). However, it's much more consistent than writing tests, including a new file and then suddenly your tests may or may not become uncompilable because the file length reached some arbitrary threshold.

We're planning to significantly increase generator speed with @TadeasKriz when our current workload lessens a bit. I think adding an option to minify the generated code might be another good area to explore to optimize the experience for users that don't feel like looking at the generated code. I feel like this could help your use-case as well.
