### ISSUE TITLE
ImplicitlyUnwrappedOptionals are being deprecated in Swift 4.2

### ISSUE THREAD

**Issue by macduy** [Brightify/Cuckoo#221]
Hi

We are using Cuckoo 0.11.3 and our project builds in Swift 4.1 and noticed this warning in the generated mocks:

```
Using ‘!’ in this location is deprecated and will be removed in a future release; consider changing this to ‘?’ instead
```

From my understanding, in Swift 4.2 `ImplicitlyUnwrappedOptionals` will no longer be a valid type: https://github.com/apple/swift-evolution/blob/master/proposals/0054-abolish-iuo.md#motivation

This will **break Cuckoo-generated mocks** in cases where mocked protocol or class has a IUO variable:

```swift
protocol StringIdentifier {
    var identifier: String! { get }
}
```

will generate

```swift
class StringIdentifierStub: StringIdentifier {
    
     var identifier: String! {
        get {
            return DefaultValueRegistry.defaultValue(for: (String!).self)
        }
        
        set { }
    }
}
```
The `(String!).self` type gives a warning in Swift 4.1. and will become an error in Swift 4.2. A manual fix would be use a cast to the optional type instead:

```swift
return DefaultValueRegistry.defaultValue(for: (String?).self)
```

Do you think this can achieved? I'm guessing the change could be made here, but I'm not very familiar with Stencil.

https://github.com/Brightify/Cuckoo/blob/0a5c4f7f1d9d56e57e81a9854e5b572ba1186350/Generator/Source/CuckooGeneratorFramework/Templates/NopImplStubTemplate.swift#L14

**Comment by gsabatie** [comment]
I have the same issue

**Comment by MatyasKriz** [comment]
I'll look into it, though it probably won't affect the Stencil template at all. Stencil uses serialized data (think `Dictionary<String, Any>` or `[String: Any]`) to fill the templates. Stencil itself has some text-processing available, but it's quite limited.

That's why I think this issue will have to be addressed in Swift code, probably during processing, not during serializing.

However first I need to do some research on the locations where the implicitly unwrapped optional will be deprecated, so that we don't turn all `!`'s into `?`'s if it's not necessary.

Thanks for the detailed report, though! If you've already done some research on this and checked the locations, I'd appreciate you sharing it with me to make my time fixing this easier.

**Comment by macduy** [comment]
Thanks Matyas, my original guess was based on being only familiar with Stencil. I recall that Stencil provides a way to check if the type is optional. If there is a better way of doing it, no doubt you'd know about it.
