### ISSUE TITLE
Dealing with internal fields

### ISSUE THREAD

**Issue by pffan91** [Brightify/Cuckoo#258]
I have an error inside generated file: *Overriding var must be as accessible as its enclosing type Insert 'public'*
But field is not public, it has an internal type:

In original file:
   ```
   internal var disposable: Disposable? = nil
   ```

In generated file:
   ```
  override var disposable: Disposable? {
        get {
            return cuckoo_manager.getter("disposable",
                superclassCall:
                    
                    super.disposable
                    ,
                defaultCall: __defaultImplStub!.disposable)
        }
        
        set {
            cuckoo_manager.setter("disposable",
                value: newValue,
                superclassCall:
                    
                    super.disposable = newValue
                    ,
                defaultCall: __defaultImplStub!.disposable = newValue)
        }
        
    }
```

What I am doing wrong? Thank you for your answers!

**Comment by MatyasKriz** [comment]
Hey, I tried using an `internal` field and this error occurred when the class in which the `internal` field was situated in was `public` itself.

This does need to be fixed in Cuckoo, however. This new info might help you workaround this issue before the fix is pushed. Alternatively, you can ignore the class that causes this issue for now.

**Comment by MatyasKriz** [comment]
I've whipped out a fix in the `internal-issues` branch, you can reference that branch directly. If you do, please let me know whether it works or not!

Thanks for the reported issue. Have a nice day!

**Comment by pffan91** [comment]
@MatyasKriz still not working for me, I am using pod 'Cuckoo', :git => 'https://github.com/Brightify/Cuckoo.git', :branch => 'internal-issues' , still got errors "Overriding var must be as accessible as its enclosing type"

P.S. Yes, the class is public but inside it has internal fields.

**Comment by MatyasKriz** [comment]
You probably still have an old version of Cuckoo generator. Please use `--clean` argument when using the `run` script in build phases.

**Comment by pffan91** [comment]
@MatyasKriz it worked with `clean` command, thank you!

**Comment by MatyasKriz** [comment]
@pffan91 no problem, although probably don't keep using the `--clean` argument, it builds the generator every time, significantly increasing your build time, instead of skipping the build when a generator is found as is done by default.

That's also why I needed you to use the `--clean` command, currently, we aren't checking whether Cuckoo and the Cuckoo generator are the same version. In the future we might add an argument to enforce this and rebuild the generator (or download it) if it finds out that the generator isn't the matching version.

**Comment by MatyasKriz** [comment]
Merged!
