### ISSUE TITLE
Workflow TDD best practices for new functions etc.

### ISSUE THREAD

**Issue by Ufosek** [Brightify/Cuckoo#276]
Hello,

I am using Cuckoo in my project for about 2 weeks. In overall it is very useful because it's similar to Mockito. I added generator in run script and set `--no-class-mocking` because I want to test only protocols.
If I have to test already implemented module (sometimes you have to) I just add it as input files in run script, write tests and voila. However I try to maintain proper TDD approach so I write test that would fail, then add implementation / refactor. It means many changes in sources and each time I add method to my testable protocol I cannot build test target because in GeneratedMocks mocks and stubs do not implement it yet (`MockMyProtocol` does not conform to protocol `MyProtocol`). So I have to clear this file and run test to generate this file again. I cannot run test that uses Cukoo because it will not see my mocked protocols so I have to remove it from target, run test that does not use Cuckoo, and then get back to my Cuckoo tests.
I think I am missing something and there should be better way to handle it but I cannot figure it out. Could you help me a bit how to improve this process?

EXAMPLE for clarity:
1. Create MyProtocol:
```
protocol MyProtocol {
//
}
```
2. Create fail test:
```
func testClick() {
   let myModule = MockMyProtocol()
   let presenter = Presenter(myModule)
   presenter.click()
   verify(myModule).show()
}
```
3. Add method and implementation
```
protocol MyProtocol {
    func show()
}
...
class Presenter {
   ...
   func click() {
      myModule.show()
   }
}
```
4. Here I would like to run my test but I cannot because it will not build: `MockMyProtocol' does not conform to protocol 'MyProtocol`
5. I have to clear GeneratedMocks file
6. I have to remove test file from target (or comment test)
7. Generate mocks (e.g. by running any test)
8. Uncomment my test and run it

Regards

**Comment by MatyasKriz** [comment]
Hey there, thanks for using Cuckoo!

If your `MyProtocol` is inside a file from which mocks are generated (the input files), it should be already mocked the next time you run the tests because the script that runs the generator does so before the build of source files. I would expect that the fact that you first created the test and then the implementation is irrelevant, because when you run testing, the generator reads your protocol with the method inside it, generates mocks, compiles them along with your tests and then runs your tests. If I don't understand this correctly, please feel free to try to explain it to me again.

Make sure that the run script is run before building/compiling of the source files. Another potential solution I can think of is moving the `GeneratedMocks.swift` file to the top of the build sources phase, so it gets compiled first.

Also, please edit your issue to properly change the names so that they are consistent. At the moment it's confusing to read `MyProtocol` one time and `MyModule` another time.

**Comment by TadeasKriz** [comment]
Hi @Ufosek, I think this is caused by Xcode's build system where it tries to not run scripts it deems that don't need running. Which files do you have set as "Input Files" and which files do you have set as "Output Files" in the build script configuration?

**Comment by Ufosek** [comment]
@MatyasKriz 

> Make sure that the run script is run before building/compiling of the source files

That was it! I forgot to move run script before compiling sources in Build Phases
