### ISSUE TITLE
any() does not compile with optional params

### ISSUE THREAD

**Issue by adotor** [Brightify/Cuckoo#279]
Version: 1.0.0

`any()` parameter matcher does not compile when used for stubbing or verifying optional paramaters.

Example:
```
class MyClass {
  func doSomething(param: String?) {
        ...
  }
}
```

Example stubbing:
```
MockMyClass().stubbing() {
  when(doSomething(param: any())).thenDoNothing()
}
```

This produces a compile error: "Generic parameter 'T' cannot be inferred."

`anyString()` works though, but in case of complex types and closures `any()` this is without alternative.

**Comment by niknar266** [comment]
I've just ran into this too. The following seems to work for me:
Replace:
```Swift
any()
```
With:
```Swift
any(Type.self)
```

**Comment by TadeasKriz** [comment]
We'll trying different ways to make `any()` working again. We'll let you know when we resolve this.

**Comment by MatyasKriz** [comment]
Hey, with the help of @TadeasKriz we managed to get it working again using only `any()`. Please give it a try with version `1.0.1`. Don't forget to use the `--clean` build option when running the `run` script, so that the new generator is used that supports this.

If the issue persists, please feel free to reopen the issue.
