### ISSUE TITLE
Stubbing optional vars does not accept `nil`

### ISSUE THREAD

**Issue by adotor** [Brightify/Cuckoo#281]
Version: 1.0.1

With the new version the stubbing for optional vars does not compile in the case `nil` is returned.

Example:
```
class MyClass {
  var optionalVar: SecTrust?
}
```

Example stubbing:
```
MockMyClass().stubbing { stub in
  when(stub.optionalVar.get).thenReturn(nil)
}
```

This produces the compiler error: 'nil' is not compatible with expected argument type 'SecTrust'"

**Related issue:** If I use "non-nil" values everywhere it compiles but the tests fail during runtime due to a missing stub: "No stub for method `optionalVar#get` using parameters ()."

**Comment by MatyasKriz** [comment]
Hey, I'm a bit confused by this. By `call MyClass` do you mean `class MyClass`? Otherwise I don't know what is that supposed to mean.

Moving onto the stubbing itself, this very functionality is tested in [the passing tests](https://github.com/Brightify/Cuckoo/blob/master/Tests/ClassTest.swift#L66). Please make sure that you have the latest generator at hand using the `--clean` build option when running the `run` script, so it would start as `run --clean generate`. This is only needed once, after that it only prolongs build times because it forces the generator to build every time.

Cuckoo also doesn't offer the `stubbing` API that you're using here, if the problem persists with the newest generator, please let me know, it could be caused by that.

**Comment by adotor** [comment]
Sorry, I for the typos in the example, this was introduced when editing the message.

Thanks for your support. I check the clean option and will come back to you.

**Comment by adotor** [comment]
@MatyasKriz I used --clean and also purged DreivedData and everything. No success, still the same error. Same with the downloaded generator (our default).

**Comment by MatyasKriz** [comment]
This seems to me like the issue is somewhere else. Could you please first try with the original API that Cuckoo offers? The `stub(mock) { ... }`.

If that doesn't do it, I'd have to request a minimal working example of this. Please file a PR to Cuckoo with a minimal class and tests that fail with the `thenReturn(nil)`. You'll get help much faster, because we'll be able to work on it here and it will prevent future bugs from being implemented.

**Comment by adotor** [comment]
I can confirm it is the same with the `stub(mock) {}`-API.

**Comment by adotor** [comment]
I can see clearly that you have already a test for this in `ClassTest::testOptionalProperty` which is "green". Hmmm.

**Comment by adotor** [comment]
Its failing for optional read only properties. I wrote the tests but must now figure out how to push the branch to github (its currently denied, have to check this).

**Comment by MatyasKriz** [comment]
Yeah, nice job finding that out. I didn't think about that possibility.

If you find that version `1.0.3` works for you, please close this issue. Otherwise we can discuss this further.

Oh and keep these reports coming, they are super useful. Thanks again!

**Comment by adotor** [comment]
It works. Thank you.
