### ISSUE TITLE
Code Coverage issue - Super methods are not calling from mock file.

### ISSUE THREAD

**Issue by krishnaSoni2113** [Brightify/Cuckoo#287]
Hello Team

I am facing an issue when i am mocking the function then the super method is not calling that's why my code coverage is always remain 0%
Here is the my test code

```
describe("checking") {
            context("HomeViewModel") {
                
                // MARK:- checking refresh method
                it("should execute the refresh() function") {
                    
                    var isRefreshCalled = false
                    
                    stub(mockHomeViewModel) { stub in
                        
                        when(stub.refresh()).then { _ in
                            isRefreshCalled = true
                        }
                    }
                    
                    mockHomeViewModel.refresh()
                    
                    expect(isRefreshCalled).to(beTrue())
                    verify(mockHomeViewModel).refresh()
                }
       }
}
```

This is mock file code and from this code the super.refresh() is not calling

```
override func refresh()  {
        
    return cuckoo_manager.call("refresh()",
            parameters: (),
            escapingParameters: (),
            superclassCall:
                
                super.refresh()
                ,
            defaultCall: __defaultImplStub!.refresh())
        
    }
```

**Comment by JIVIJA** [comment]
I am getting same issue. The super method are not getting called in actual/super file we are testing. Thats why we are getting code coverage 0%.

![Screenshot 2019-05-24 at 6 30 59 PM](https://user-images.githubusercontent.com/16122807/58329819-16b72f00-7e53-11e9-8435-62e7bbe9f6fa.png)

**Comment by krishnaSoni2113** [comment]
@JIVIJA Exactly, same issue.
Please let me know if you found any solution on same.

**Comment by TadeasKriz** [comment]
Hey @krishnaSoni2113 @JIVIJA, the super is not supposed to be called. You can tell Cuckoo to call it when stubbing, which would be something like (the name might be a bit different, I don't recall):

```
 stub(mockHomeViewModel) { stub in                
    when(stub.refresh()).thenCallRealmImplementation()
}
```

However, this is not what you want to do. Code coverage is for classes you are testing. When you mock something, you're not testing it and thus having `0%` coverage is the expected and correct result.

The code you've shown is a great example. You stub a method `refresh` and rewrite it's behavior to set the `isRefreshCalled` to `true`. That means you didn't really run the `refresh` method of your ViewModel and so it didn't get tested.

Mocks are supposed to be used as a replacement for dependencies that the class you're testing needs. For example, if you were testing some `ViewController` that was dependent on your `HomeViewModel`, then you could give the mocked `HomeViewModel` to the controller and verify that the `ViewController` does exactly what it should do.

Please do more research on how to write tests and how to use mocks, because when you write tests like you've shown in the example, they aren't really tests and give you 0 coverage as a result.
