### ISSUE TITLE
Public protocol's property not public

### ISSUE THREAD

**Issue by Daedren** [Brightify/Cuckoo#303]
Hello, apologies for nagging again, but I've hit yet another issue, using the same example as #301

I've tested this on Cuckoo 1.1.0

The following protocol's generated mock won't compile

```swift
public protocol TestProtocol {
    associatedtype TestAssocType
    var strProperty: String {get set}
}
```

Due to an error: **Property 'strProperty' must be declared public because it matches a requirement in public protocol 'TestProtocol'**

On the following excerpt of the generated mocks, *strProperty* is non-public, which triggers the compiler error.

```swift
public class MockTestProtocol<TestAssocType>: TestProtocol, Cuckoo.ProtocolMock {
    
    public typealias MocksType = DefaultImplCaller<TestAssocType>
    
    public typealias Stubbing = __StubbingProxy_TestProtocol
    public typealias Verification = __VerificationProxy_TestProtocol

    public let cuckoo_manager = Cuckoo.MockManager.preconfiguredManager ?? Cuckoo.MockManager(hasParent: false)

    
	public class DefaultImplCaller<TestAssocType>: TestProtocol {
	    private let reference: Any
	
	    private let _getter_storage$$strProperty: () -> String
	    private let _setter_storage$$strProperty: (String) -> Void
	    var strProperty: String {
	        get { return _getter_storage$$strProperty() }
	        set { _setter_storage$$strProperty(newValue) }
	    }
...
```

Let me know if I'm missing something or if you need more information. 
Thank you for your great work on Cuckoo.

**Comment by MatyasKriz** [comment]
Hey, thanks for the report. As it turns out, I was the murderer and you found my murder. At first I "fixed" the issue, then I reverted it, because it didn't work for all use-cases and some users rightfully complained.

Now I added it to places where I forgot – to protocol templates as well as adding this test case to the testing protocols, so that we can catch this automatically when running tests.

It will be released in `1.1.1`. Have a nice day.
