### ISSUE TITLE
Not generated Mocks in GeneratedMocks.swift

### ISSUE THREAD

**Issue by fevicks** [Brightify/Cuckoo#343]
I used swift package manager, but mock is not generated
In Run Script
```
OUTPUT_FILE="${PROJECT_DIR}/${PROJECT_NAME}Tests/GeneratedMocks.swift"
echo "Generated Mocks File = ${OUTPUT_FILE}"
INPUT_DIR="${PROJECT_DIR}/${PROJECT_NAME}"
echo "Mocks Input Directory = ${INPUT_DIR}"
"${PROJECT_DIR}/run" --download generate --testable "${PROJECT_NAME}" \
--output "${OUTPUT_FILE}" \
"${INPUT_DIR}/ViewController"
```

then from terminal - i used the below command
```
curl -Lo run https://raw.githubusercontent.com/Brightify/Cuckoo/master/run && chmod +x run
```

its generated "GeneratedMocks.swift" - just file is generated not the mock for "${INPUT_DIR}/ViewController", show i configure any other things for swift PM?

**Comment by MatyasKriz** [comment]
Hey there, I know the issue is closed, but I was just wondering if you discovered the `--glob` flag which allows you to use `${INPUT_DIR}/ViewController/*.swift` or even `${INPUT_DIR}/ViewController/**/*.swift`. Of course you can specify all the files manually, but if you want to mock all of them, this is the most concise way.
