### ISSUE TITLE
How to Verify Delegate(Callback) method is called

### ISSUE THREAD

**Issue by fevicks** [Brightify/Cuckoo#344]
Below is my code
```
**LoginViewController.swift**
class LoginViewController: UIViewController {
    private let controller: LoginController
    init(controller: LoginController) {
        self.controller = controller
        controller.delegate = self
    }
    @IBAction func login(_ sender: Any) {
        controller.login(id: "", password: "")
    }
}

extension LoginViewController: LoginControllerDelegate {
    func didLogin(_ message: String) {
        showAlert(title: "Sucess", message: message)
    }
}

```

```
**LoginController.swift**
protocol LoginControllerDelegate: class {
    func didLogin(_ message: String)
}

class LoginController {
    weak var delegate: LoginControllerDelegate?

    func login(id: String, password: String) {
        // Some Validation
        performLogin(id: String, password: String)
    }
    func performLogin(id: String, password: String) {
        self.delegate.didLogin("You logged in")
    }    
}
```

In the above code how i can **verify**  _func didLogin(_ message: String)  is called If **login** Button Action called

Currently i am doing like below(just verify login method of controller is called), but i don't know how to verify _func didLogin(_ message: String) is called
```
    func test_loginSuccessMethodCalledOnLoginAction(){
        stub(mockController) { (stubbingProxy) in
            when(stubbingProxy.login(idOrIqamaNumber: "", password: "")).thenDoNothing()
        }
        viewController.login(UIButton())
        verify(mockController, times(1)).login(idOrIqamaNumber: "", password: "")
    }
```

**Comment by MatyasKriz** [comment]
Hey, @fevicks.

Unfortunately, due to Swift limitation, Cuckoo can't override methods in extensions which is the mechanism that is used for mocking. If you need to mock a method, it needs to be in the class body. So you will need to merge that extension along with the protocol conformance with the class itself.

After that, mocking works the same way as anywhere else. I created a simple test case:

```
func test344() {
    let controller = LoginController()
    let mock = MockLoginViewController(controller: controller)

    stub(mock) { stub in
        when(stub.didLogin(any())).then { print("gg? - \($0)") }
    }

    controller.login()

    verify(mock).didLogin(any())
}
```

By the way, `times(1)` is the default value when verifying, you can omit it from the call.

Also, it is recommended to use `AnyObject` with protocols enforcing object type instead of `class`.

Let me know if this makes sense and close the issue if this is resolved, thanks!

**Comment by fevicks** [comment]
@MatyasKriz thanks for your quick response, I am confusing actually, i want to test in **LoginViewController** - when i click on login button, i need to make sure LoginViewController(test class), delegate implementation **didLogin** is called, but in your sample test cases you created mock for **LoginViewController**, why we have to create mock for the same class which we are going to test, as we are testing **LoginViewController**, if i did some mistake please guid me, By the way shall you invite me to your slack channel "fevicks@gmail.com"

**Comment by MatyasKriz** [comment]
Hey, @fevicks. I'm not sure what you mean, but as far as I know, if you want to verify `didLogin` call, you need to mock `LoginControllerDelegate`, not `LoginViewController`.

This is how it might look if you want to test `LoginController` validation:
```
func test344() {
    let controller = LoginController()
    let mock = MockLoginControllerDelegate()
    controller.delegate = mock

    stub(mock) { stub in
        when(stub.didLogin(any())).then { print("gg? - \($0)") }
    }

    controller.login()

    verify(mock).didLogin(any())
}
```

However, if you really just want to test that tapping a login button calls all the way back to the `LoginControllerDelegate` (in your case it's the `LoginViewController`), this is the code that will do it:
```
func test344() {
    let controller = LoginController()
    let viewController = LoginViewController(controller: controller)
    let mock = MockLoginControllerDelegate()
    // Override the delegate set by `LoginViewController` so we can verify the call.
    controller.delegate = mock

    stub(mock) { stub in
        when(stub.didLogin(any())).then { print("gg? - \($0)") }
    }

    viewController.login(UIView())

    verify(mock).didLogin(any())
}
```

By overriding the delegate on `LoginController` after instantiating `LoginViewController`, we are able to verify the `didLogin` call.

BTW, we don't really use Slack at the moment, as it was most of the time just one-time issues, which can really be discussed here on GitHub where it's easier to keep track of and where they're easier to discover.

If this is what you wanted, please close the issue, otherwise we can discuss this further.

**Comment by MatyasKriz** [comment]
I'll close the issue for now, if there is still some confusion, we can discuss it further.
