### ISSUE TITLE
Import statement is added any time "import something" is found in a comment

### ISSUE THREAD

**Issue by dbreese** [Brightify/Cuckoo#397]
Take this class, for example:

`
import Foundation

// some comment has import SOMEBADTHING
public protocol TestProtocol: AnyObject {
  func doSomething() -> Void
}
`

The generated mock ends up having:

`
...
import SOMEBADTHING
...
`

Looks like it is looking for "{import .*}" in source files and just adding that verbatim to the output file, causing compile issues.

**Comment by MatyasKriz** [comment]
Thanks for the report, probably a regex too simple for its own good.

**Comment by MatyasKriz** [comment]
> Hi, want to fix this issue in the near future, can I?

Hey, thanks for bringing this issue to my attention. Honestly I thought it was long fixed, though with the switch to SwiftSyntax I'm fairly certain that this issue is resolved.

If you'd like to help me verify that, follow the instructions in the 2.0 pre-release: https://github.com/Brightify/Cuckoo/releases/tag/2.0.0-beta.1
