### ISSUE TITLE
GeneratedMocks modified during Build Phase Xcode 13

### ISSUE THREAD

**Issue by bratxdy** [Brightify/Cuckoo#400]
Starting in Xcode 13 we started getting errors around Cuckoo that the GeneratedMocks file was modified during build time. It seems like this could be an Xcode 13 issue as it doesn't seem to be respecting Output Files, but is there anything you guys can do on your end to fix this? Or do you know of any tips for fixing this on the integration side? We've been using Cuckoo for a couple years and have never had issues until Xcode 13. We are using input files lists for the list of mocks we want and an output file for the GeneratedMocks class. Our build phase is right before the Compile Sources build phase.

**Comment by robot9xvt** [comment]
Me too

**Comment by JavaAdam** [comment]
I have the same issue as others too. See for a workaround: https://stackoverflow.com/questions/69256241/xcode-13-error-input-file-was-modified-during-the-build 

The official Apple feedback to me was to use build rules instead of build phases. They recommended to watch this here: https://developer.apple.com/videos/play/wwdc2021/10210/?time=379

But I think this does not match the requirements, because for Cuckoo we do not have different file extensions. So I could not define a fitting build rule to avoid the build errors. Either it was not working or the source swift files to be mocked were compiled twice. I am curious what will be the next answer from apple.

**Comment by bratxdy** [comment]
I have tried the workout in that Stackoverflow, but the issue still occurs using an xcfilelist for the output file.

**Comment by JavaAdam** [comment]
At the end the workaround does also not worked for me. But the error occurs more seldom.

**Comment by dhaval12593** [comment]
We are facing the same issue.

**Comment by mjholgate** [comment]
I think I may have figured this out. In our case we are not using Cuckoo, but it is likely a similar problem to what you are seeing.

At times we end with background builds happening (e.g. for Swift UI Previews), and if those run concurrently with our main build, sometimes this will cause the main build to spot that the background build has changed the file.

I think the problem is that the build phase is creating files in the shared source tree rather than the derived output folder. That being said, I'm not sure how to make a generated file in the derived output file be referenced from the xcode project :-(.

**Comment by mjholgate** [comment]
The trick I think is to make sure all your output files from your script are written to somewhere within $(DERIVED_FILE_DIR).

So your input xcfilelist should normally contain files relative to $(SRCROOT), and your output xcfilelist should only contain files relative to $(DERIVED_FILE_DIR). This will ensure that each separate build instance writes only to its own files.

You can then add the output files to your target by navigating to:

/Users/<user>/Library/Developer/Xcode/DerivedData/<App>-*/Index/Build/Intermediates.noindex/<App>.build/Debug-iphonesimulator/<Target>.build/DerivedSources

Once you've added the files, make sure to open them in the file navigator and make sure they are accessed relative to build products:

![screenshot_1446](https://user-images.githubusercontent.com/1170271/136236658-783621c2-3fd2-47a3-9ac8-9898ab52b8a7.png)

This should mean that each build only accesses its own instances of files.

**Comment by JavaAdam** [comment]
> I'm investigating the [same issue for R.swift](https://github.com/mac-cain13/R.swift/issues/719).
> 
> I think the issue is caused by the Indexer running at the same time as the build. Xcode 13 seems to execute Run Scripts during indexing as well.
> 
> The fix is to only run the code generator during builds, not indexing:
> 
> ```shell
> if [ $ACTION != "indexbuild" ]; then
>   # your script here 
> fi
> ```

It seems that this works for me also. Thank you @tomlokhorst!

**Comment by TadeasKriz** [comment]
Oh I didn't know that and I didn't want to take your contribution away from you. I'll go ahead and update it then, thank you!

**Comment by jazminebarroga** [comment]
Anyone else still experiences this issue even with the proposed solution?
