### ISSUE TITLE
Async/await support

### ISSUE THREAD

**Issue by austinrovge** [Brightify/Cuckoo#407]
Now that Swift 5.5 is released and async/await will be back deployed to iOS 13 in Xcode 13.2, I'm getting ready to update my app to take advantage of it.

Is there any ongoing or planned work for adding support for async functions/properties/initializers, actors, etc? I'm interested in contributing to this feature, though I don't have a lot of free time at the moment.

**Comment by MatyasKriz** [comment]
Hey, @austinrovge, I was thinking about this blocking users as well. Unfortunately I'm not strong in the free time department either.

SourceKitten seems to support this since [0.31.1](https://github.com/jpsim/SourceKitten/releases/tag/0.31.1), so we should be able to get this information pretty easily once it's updated. If you're up for it, by all means, go for implementing this. 🙂 Please include a few simple test cases along with it.
