### ISSUE TITLE
Cuckoo need XCTest.framework in link binary with Libraries section. otherwise it shows error that is "cannot find 'XCTFail' in scope" in MockManager.swift file

### ISSUE THREAD

**Issue by LieonShelly** [Brightify/Cuckoo#469]
here is how to reproduce this issue
- there is no XCTest.framework in link binary with Libraries section. it shows "cannot find 'XCTFail' in scope" in MockManager.swift file
-  Add XCTest.framework in link binary with Libraries section, it build success.

I integrated this framework with tuist. pls help to check, thx

<img width="1356" alt="截屏2023-06-05 18 45 23" src="https://github.com/Brightify/Cuckoo/assets/16146746/80c8ebc6-3a7b-43b4-bef1-44081eb89184">

success with XCTest.framework 
<img width="1241" alt="截屏2023-06-05 18 39 28" src="https://github.com/Brightify/Cuckoo/assets/16146746/3c781e2f-f658-4c8c-a82d-bfb4626e03d1">

fail without XCTest.framework 
<img width="1147" alt="截屏2023-06-05 18 39 10" src="https://github.com/Brightify/Cuckoo/assets/16146746/38392001-48c1-4940-aee8-bd3cc2f31b62">

**Comment by MatyasKriz** [comment]
Hey there, are you sure you're using Cuckoo in a unit test target? Because SPM is supported for quite some time and there haven't been any complaints of this nature so far unless it was added to the wrong target.

You can find our dependency on XCTest in the `Project.swift` manifest, I'm not sure why anything else would be necessary, what Xcode version are you using?
