### ISSUE TITLE
Cuckoo lacks support for static functions

### ISSUE THREAD

**Issue by lvdstam** [Brightify/Cuckoo#93]
When a protocol contains a static function, the generated mock does not conform to the protocol because the static function is not generated for the mock implementation.

protocol SomeProtocl {
    static func someFunction()
}

**Comment by cohenadair** [comment]
Due to the way Swift works, static functions will not be supported.  See the [What will not be supported](https://github.com/Brightify/Cuckoo#what-will-not-be-supported) section in the README.

**Comment by samskiter** [comment]
Hey, could you elaborate on why this is a little more please? I don't see overrides used anywhere in my generated mocks.

**Comment by cohenadair** [comment]
I don't actually know what the generated code looks like (I ended up just creating my own mocks in the end), so I can't comment on what the generated code looks like.

From the README:
> [The generated mocks] work based on inheritance and protocol adoption. This means that only overridable things can be mocked.

Static methods aren't overridable, and therefore can't be mocked by Cuckoo.  Why mocks were implemented this way, I don't know; that is a question for a Cuckoo developer.

**Comment by TadeasKriz** [comment]
Static methods are being called directly by Swift, so there's no way to mock them (as far as I know). When Cuckoo generates a mock for a protocol there are no `override` keywords as it's implementing those methods and not overriding them. On the other hand, when generating a mock for a class, there will be `override` keywords for those methods.

But the problem with static methods isn't in the overriding. It's because Swift calls `static` methods directly, without any dynamic dispatch. The only possible way to take advantage of mocking `class` methods/properties would be if you has an instance and used `type(of: instance).aClassMethod()` in your code. If that's the case, I believe we could add this support, but it would require a proper documentation to not confuse users about its purpose.

What do you think?

**Comment by samskiter** [comment]
I've used a protocol with a static method in the past, then written a real
and mocked implementation of that. Mymockimplemetation.self let me pass it
into the class I needed to inject it into

**Comment by TadeasKriz** [comment]
Hm, you're right, that would make sense to have. The only limitation would then become the state. You would have to reset the static manager in each test method you use it. Probably using `defer { staticMock(AClass).reset() }` or something like that.

**Comment by samskiter** [comment]
Or just put it in the teardown method. If there were some global way of
detecting test tear down that would be useful

**Comment by samskiter** [comment]
https://github.com/apple/swift-corelibs-xctest/pull/102 perhaps useful?

**Comment by MatyasKriz** [comment]
Hey there! If you happen to still be battling this issue, try using `class func`. They are overridable, so in theory they should work. In the meantime I'll close this issue for now, you can open a new one if `class func` can't be mocked either. 🙂

**Comment by samskiter** [comment]
Hey, just bumped into this exact problem again, you can't use `class func` in a protocol declaration unfortunately

**Comment by samskiter** [comment]
cc @MatyasKriz

**Comment by MatyasKriz** [comment]
Hey, @samskiter. Leveraging the OCMock support might help in your endeavor. If it's needed in pure Swift and you've got an idea of implementing it, by all means go for it and file a PR, I'll gladly look it over and merge it, it seems like a good addition. Let me know if you need help with contributing!
